/* -*- Mode: C; c-basic-offset:4 ; indent-tabs-mode:nil -*- */
/*
 * Copyright (c) 2004-2005 The Trustees of Indiana University and Indiana
 *                         University Research and Technology
 *                         Corporation.  All rights reserved.
 * Copyright (c) 2004-2014 The University of Tennessee and The University
 *                         of Tennessee Research Foundation.  All rights
 *                         reserved.
 * Copyright (c) 2004-2005 High Performance Computing Center Stuttgart,
 *                         University of Stuttgart.  All rights reserved.
 * Copyright (c) 2004-2005 The Regents of the University of California.
 *                         All rights reserved.
 * Copyright (c) 2006      Los Alamos National Security, LLC.  All rights
 *                         reserved.
 * Copyright (c) 2008-2015 Cisco Systems, Inc.  All rights reserved.
 * Copyright (c) 2009      Oak Ridge National Labs.  All rights reserved.
 * Copyright (c) 2010-2014 Los Alamos National Security, LLC.
 *                         All rights reserved.
 * Copyright (c) 2014      Hochschule Esslingen.  All rights reserved.
 * Copyright (c) 2015      Research Organization for Information Science
 *                         and Technology (RIST). All rights reserved.
 * Copyright (c) 2015      Mellanox Technologies, Inc.
 *                         All rights reserved.
 * Copyright (c) 2016      Intel, Inc. All rights reserved.
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 */

#include "gds_config.h"

#include "src/include/types.h"
#include "src/mca/base/gds_mca_base_var.h"
#include "src/runtime/gds_rte.h"
#include "src/util/timings.h"

#if GDS_ENABLE_TIMING
char *gds_timing_sync_file = NULL;
char *gds_timing_output = NULL;
bool gds_timing_overhead = true;
#endif

static bool gds_register_done = false;

gds_status_t gds_register_params(void)
{
    if (gds_register_done) {
        return GDS_SUCCESS;
    }

    gds_register_done = true;

#if GDS_ENABLE_TIMING
    gds_timing_sync_file = NULL;
    (void) gds_mca_base_var_register ("gds", "gds", NULL, "timing_sync_file",
                                  "Clock synchronisation information generated by mpisync tool. You don't need to touch this if you use mpirun_prof tool.",
                                  GDS_MCA_BASE_VAR_TYPE_STRING, NULL, 0, 0,
                                  GDS_INFO_LVL_9, GDS_MCA_BASE_VAR_SCOPE_ALL,
                                  &gds_timing_sync_file);
    if( gds_timing_clocksync_read(gds_timing_sync_file) ){
        gds_output(0, "Cannot read file %s containing clock synchronisation information\n", gds_timing_sync_file);
    }

    gds_timing_output = NULL;
    (void) gds_mca_base_var_register ("gds", "gds", NULL, "timing_output",
                                  "The name of output file for timing information. If this parameter is not set then output will be directed into GDS debug channel.",
                                  GDS_MCA_BASE_VAR_TYPE_STRING, NULL, 0, 0,
                                  GDS_INFO_LVL_9, GDS_MCA_BASE_VAR_SCOPE_ALL,
                                  &gds_timing_output);

    gds_timing_overhead = true;
    (void) gds_mca_base_var_register ("gds", "gds", NULL, "timing_overhead",
                                  "Timing framework introduce additional overhead (malloc's mostly)."
                                  " The time spend in such costly routines is measured and may be accounted"
                                  " (subtracted from timestamps). 'true' means consider overhead, 'false' - ignore (default: true).",
                                  GDS_MCA_BASE_VAR_TYPE_BOOL, NULL, 0, 0,
                                  GDS_INFO_LVL_9, GDS_MCA_BASE_VAR_SCOPE_ALL,
                                  &gds_timing_overhead);
#endif

    return GDS_SUCCESS;
}

gds_status_t gds_deregister_params(void)
{
    gds_register_done = false;

    return GDS_SUCCESS;
}
