/*
 * Copyright (c) 2015     Cisco Systems, Inc.  All rights reserved.
 * Copyright (c) 2016     Intel, Inc. All rights reserved.
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 */

#ifndef GDS_GDL_GDLOPEN
#define GDS_GDL_GDLOPEN

#include <src/include/gds_config.h>

#include "src/mca/gdl/gdl.h"

extern gds_gdl_base_module_t gds_gdl_gdlopen_module;

/*
 * Dynamic library handles generated by this component.
 *
 * If we're debugging, keep a copy of the name of the file we've opened.
 */
struct gds_gdl_handle_t {
    void *dlopen_handle;
#if GDS_ENABLE_DEBUG
    void *filename;
#endif
};

typedef struct {
    gds_gdl_base_component_t base;

    char *filename_suffixes_mca_storage;
    char **filename_suffixes;
} gds_gdl_gdlopen_component_t;

extern gds_gdl_gdlopen_component_t mca_gdl_gdlopen_component;

#endif /* GDS_GDL_GDLOPEN */
